name: whoami_webfe
services:
    - build_command: npm run build
      environment_slug: node-js
      github:
          branch: main
          deploy_on_push: true
          repo: np1e/whoami_webfrontend
